apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-frontend-green
  labels:
    app: sa-frontend-green
spec:
  selector:
    matchLabels:
      app: sa-frontend-green
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sa-frontend-green
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
          name: sa-frontend-green
          ports:
            - containerPort: 80
