apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-frontend
  namespace: sa-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-frontend
  namespace: sa-frontend
  labels:
    app: sa-frontend
spec:
  selector:
    matchLabels:
      app: sa-frontend
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sa-frontend
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: sa-frontend
      containers:
        - image: gcr.io/apt-index-377201/sentiment-analysis-frontend:efa4df4e6b88af86d48ce02aa344db7ab74c7e8a
          imagePullPolicy: Always
          name: sa-frontend
          ports:
            - containerPort: 80
