apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-logic
  namespace: sa-logic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-logic
  labels:
    app: sa-logic
  namespace: sa-logic
spec:
  selector:
     matchLabels:
       app: sa-logic
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sa-logic
    spec:
      serviceAccountName: sa-logic
      containers:
        - image: gcr.io/apt-index-377201/sentiment-analysis-logic:3b81d14c77cbe341f57538d4cfc39f0f6ddb13a6
          imagePullPolicy: Always
          name: sa-logic
          ports:
            - containerPort: 5000
